version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: dnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
 #   networks:   
 #     - net-php
 #     - net-nginx


  php:
    #build: ./php/php72/
    image: php_self:v8
    container_name: dnmp-php
    expose:
      - "9000"
    volumes:
      - ../:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
     # - ./php/init.sh:/var/www/init.sh:rw
      - ./php/hosts:/var/www/hosts:rw
    #entrypoint: /bin/bash

  redis:
    image: redis:latest
    container_name: dnmp-redis
    #networks:
       #- net-redis
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    container_name: dnmp-memcached
   # networks:
   #   - net-memcached
    ports:
      - "11211:11211"



    #command: /var/www/init.sh

 #   networks:
 #    - net-php
 #     - net-mysql
 #     - net-redis
 #   extra_hosts:
 #     - dev-cc.inboyu.com:172.22.0.3
 #     - dev-uc.inboyu.com:172.22.0.3
 #     - dev-md.inboyu.com:172.22.0.3

 # mysql:
 #   image: mysql:latest
 #   container_name: dnmp-mysql
 #   ports:
 #     - "3306:3306"
 #   volumes:
 #     - ./conf/my.cnf:/etc/mysql/my.cnf:ro
 #     - ./mysql/:/var/lib/mysql/:rw
 #     - ./log/:/var/log/dnmp/:rw
#    networks:
#      - net-mysql
 #   environment:
 #     MYSQL_ROOT_PASSWORD: "123456"

 # redis:
 #   image: redis:latest
 #   container_name: dnmp-redis
 #    networks:
 #      - net-redis
 #   ports:
 #     - "6379:6379"

#networks:
#  net-php:
#  net-mysql:
#  net-redis:
#  net-nginx:

#同一网络上不需要定义网络直接使用服务名称 就可以访问对应容器 
